### ISSUE TITLE
[Enhance] 对 `Docker` 支持 `jq` 和 `yq` 实现自动换源

### ISSUE THREAD

**Issue by ccmywish** [RubyMetric/chsrc#100]
https://github.com/RubyMetric/chsrc/issues/35#issuecomment-2408303823

**Comment by happy-game** [comment]
既然目前的源文件只有docker是使用json格式，那我感觉直接使用sed替换"registry-mirrors": [xxx]为"registry-mirrors": [src"]更为合适，因为一些发行版(如debian)没有预装jq.
或许可以在换源前判断是否存在jq来决定使用jq还是sed换源.

**Comment by ccmywish** [comment]
Hi, @happy-game 又见面了

我目前不用 `docker`，所以我不知道它的配置文件细节到底是什么样的，如果 `sed` 能做到，当然直接就用 `sed` 了。有兴趣解决这个问题吗？时间方面看你个人自由，没有任何要求。

**Comment by happy-game** [comment]
我是看[#35 (comment)](https://github.com/RubyMetric/chsrc/issues/35#issuecomment-2408303823)中你提到

> 目前 chsrc 支持的60多个目标中，只有 docker 使用 JSON 作为配置文件（其他使用 JSON 的可以自动换源），另外有3个用 toml，1个用 yml，1个用xml，这些都无法自动换源。所以我更想引入 yq 而非 jq 来处理。但由于上述发现，并没有引入。

所以我觉得可以不用 jq, 而直接使用sed.

我会试着去解决这个问题.
