### ISSUE TITLE
[New Target] 针对Github的clone下载加速服务器

### ISSUE THREAD

**Issue by Wszl** [RubyMetric/chsrc#108]
### 描述新的换源目标

基于https://github.com/hunshcn/gh-proxy该项目的自动化命令行功能。
在使用时需要手动拼接url 如 wget https://github.com/RubyMetric/chsrc/releases/download/v0.1.9/chsrc-x64-linux
需要手动拼接为 wget https://github.com/hunshcn/gh-proxyhttps://github.com/RubyMetric/chsrc/releases/download/v0.1.9/chsrc-x64-linux
以下脚本可以自动完成拼接工作，可以为其他脚本中使用到wget  github功能进行加速
https://github.com/Wszl/mget

### 请尽可能提供可参考的换源方法

将本项目clone后。
https://github.com/Wszl/mget 
$ GITHUB_MIRROR=可用的github镜像网址

$ source /your repo path/mget.sh
即可

### 请尽可能提供已有镜像站

https://github.moeyy.xyz/

**Comment by ccmywish** [comment]
你好，感谢反馈。

有两个问题使得 `chsrc` 暂时不能提供这方面的支持

1. `chsrc` 只考虑对软件换源，并不考虑对下载行为进行换源

2. `chsrc` 提供的镜像站内置于二进制文件内，相当于间接认可这些镜像站的安全性。为了充分确保上游镜像站的可用性、稳定性和安全性，我们仅考虑教育网、大型商业公司提供的镜像服务，这些服务都已备案，可溯源。目前对GitHub的release下载，基本都是个人为主搭建的服务，我们没办法纳入其中

请见谅。

**Comment by free-150** [comment]
确实有这个需求，如果从github下载无法加速还不如开魔法，既然开了魔法还换什么源。很矛盾

**Comment by ccmywish** [comment]
@free-150 

这个需求的确存在。

魔法不是万能的，如果一切都靠魔法，费用将高不可攀。

`chsrc` 也不是银弹，`chsrc` 要解决的问题域非常清晰，只是帮助用户和合法备案审核过的镜像站之间搭建桥梁，我们不帮助用户和GitHub搭建桥梁。

请见谅。我觉得对此有需求的话，完全可以像 @Wszl 一样，直接自己写一个小的程序来完成这个任务。
