### ISSUE TITLE
[Bug] debian系统初始安装完成后更换源失败

### ISSUE THREAD

**Issue by yougg** [RubyMetric/chsrc#110]
### 你操作了什么？

sources.list中只有一条cdrom的源

```shell
cat /etc/apt/sources.list
```

> deb cdrom:[Debian GNU/Linux 12.7.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20240831-10:40]/ bookworm contrib main non-free-firmware

使用chsrc更换源失败

### 发生了什么？

![image](https://github.com/user-attachments/assets/b47a27aa-5d64-4bcf-bc32-185fe920174b)

### 本应该怎么样？

如果旧的sources没有可用源直接将其替换为指定的源

### chsrc 版本

v0.1.9-2024/10/09

### 你使用的是哪个操作系统？

Linux

### OS 版本 / OS 发行版

Debian 12 bookworm

### 防止重复问题

- [X] 我已在项目的 GitHub 和 Gitee 两个仓库分别搜索过类似的 issue

**Comment by ccmywish** [comment]
@yougg 

你先删除 `sources.list` 文件，然后重新执行 `chsrc` 试一下。之前写 Debian 的换源 recipe 的时候考虑到了这个文件缺失的情况，会生成一个新的。

**Comment by yougg** [comment]
> 你先删除 `sources.list` 文件，然后重新执行 `chsrc` 试一下。之前写 Debian 的换源 recipe 的时候考虑到了这个文件缺失的情况，会生成一个新的。

![image](https://github.com/user-attachments/assets/f8e04957-ff1e-44af-bff0-88f979556886)

删掉后识别系统版本不对了

**Comment by ccmywish** [comment]
https://github.com/RubyMetric/chsrc/blob/main/src/recipe/os/APT/common.h#L61-L66

代码在这里，你方便简单调试下吗？直接运行命令行两个 `sed` 看看结果。或者C语言里加个 `printf` 看看 `version` 是多少。

**Comment by yougg** [comment]
```shell
cat /etc/os-release 
```

> PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
> NAME="Debian GNU/Linux"
> VERSION_ID="12"
> VERSION="12 (bookworm)"
> VERSION_CODENAME=bookworm
> ID=debian
> HOME_URL="https://www.debian.org/"
> SUPPORT_URL="https://www.debian.org/support"
> BUG_REPORT_URL="https://bugs.debian.org/"

![image](https://github.com/user-attachments/assets/59976c9c-0b99-4ddd-93c0-c5ff9ffe9131)

**Comment by ccmywish** [comment]
@yougg 

修复了，可以重新按照 README 中的安装方式安装新的 `v0.1.9.2` 试下看

**Comment by yougg** [comment]
验证没问题了
