### ISSUE TITLE
域名是不是被墙了

### ISSUE THREAD

**Issue by pei92** [RubyMetric/chsrc#119]
### 你操作了什么？

我运行了 curl https:/chsrc.run/posix | sudo bash

### 发生了什么？

Could not resolve host: https; Unknown error

### 本应该怎么样？

我希望执行成功并换源

### chsrc 版本

最新版

### 你使用的是哪个操作系统？

Linux

### 防止重复问题

- [X] 我已在项目的 GitHub 和 Gitee 两个仓库分别搜索过类似的 issue

**Comment by ccmywish** [comment]
感谢反馈

https://chsrc.run/posix 访问不了的时候，可以使用 https://gitee.com/RubyMetric/chsrc/raw/main/tool/installer.sh 来代替

我已经更新README来说明这一点
