### ISSUE TITLE
[New Source] 希望测试时添加官方源

### ISSUE THREAD

**Issue by sanchuanhehe** [RubyMetric/chsrc#121]
### 描述该源

Types: deb
URIs: http://archive.ubuntu.com/ubuntu
Suites: mantic mantic-updates mantic-backports
Components: main restricted universe multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

Types: deb
URIs: http://security.ubuntu.com/ubuntu
Suites: mantic-security
Components: main restricted universe multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

**Comment by ccmywish** [comment]
@sanchuanhehe 感谢建议，会考虑的

**Comment by ccmywish** [comment]
@sanchuanhehe 

已实现，可通过 `curl https://chsrc.run/posix | sudo bash` 使用最新版测试。若无问题，可随时关闭此 issue

**Comment by sanchuanhehe** [comment]
非常感谢维护者们的工作，我也有兴趣来参与贡献，有什么我需要在此之前了解的吗

**Comment by ccmywish** [comment]
@sanchuanhehe 很高兴你有兴趣参与贡献👍 

`chsrc` 的目标是：
1. 对最终用户来说是一个实用的工具
2. 对贡献者/开发者来说，`chsrc` 的代码干净整洁，容易理解和维护，但是也足够有挑战性以支撑用户的苛刻需求
3. 对所有参与者来说，`chsrc` 项目作为一个公益互助之地，协调大家一起处理问题，获得知识和经验，赢得尊重和成就感的同时也能服务数万用户
4. ...

贡献/开发前可以先花5分钟阅读这两部分：

1. https://github.com/RubyMetric/chsrc#%EF%B8%8F-%E5%BC%80%E5%8F%91
5. https://github.com/RubyMetric/chsrc/blob/main/doc/Write-A-Recipe-Even-If-You-Dont-Know-C.md

---

`chsrc` 的代码结构非常清晰，分为 `framework`（基础的框架） 和 `recipe`（具体的每一个换源方案） 两部分。如果想要达到最理想的维护状态，每一个 recipe 都需要有专人长时间维护。所以你可以先从某一个你熟悉的、你正在使用的、你觉得可以改进的 recipe 入手。

如果你想搞清楚 `chsrc` 的工作原理，我建议你
1. 直接先看 [framework/struct.h](https://github.com/RubyMetric/chsrc/blob/main/src/framework/struct.h) 这个文件，以了解程序的核心对象
2. 然后阅读 [recipe/lang/PHP.c](https://github.com/RubyMetric/chsrc/blob/main/src/recipe/lang/PHP.c) 这个几乎最简单的 recipe 来间接思考 framework 是如何支撑 recipe 的运行的
6. 之后就可以根据疑问、好奇心按需查看 [framework/core.c](https://github.com/RubyMetric/chsrc/blob/main/src/framework/core.c) 这个文件是具体如何实现核心通用功能的

上述循序渐进的步骤能够帮助你快速而又准确地理解 `chsrc` 的原理和执行流程，此后你仅凭自己就可以定位和解决各种你自己或者他人的问题。
