### ISSUE TITLE
添加对 uv 的支持

### ISSUE THREAD

**Issue by xyx1926885268** [RubyMetric/chsrc#139]
### 描述新的换源目标

一个工具来替换 pip、pip-tools、pipx、poetry、pyenv、twine、virtualenv 等。

### 请尽可能提供可参考的换源方法

根据官方文档给出的方法：https://docs.astral.sh/uv/configuration/files/
对于在用户级别操作的工具命令，将忽略本地配置文件。相反，uv 将仅从用户级配置（例如，~/.config/uv/uv.toml）和系统级配置（例如，/etc/uv/uv.toml）中读取。
打开 uv.toml 添加如下内容：
[[index]]
url = "https://test.pypi.org/simple"
default = true
不过我用的是直接写入到系统环境变量的方法实现的：
设置 UV_INDEX_URL 变量的变量值为对应的镜像源，我也设置了 UV_EXTRA_INDEX_URL 变量为其他的镜像源作为负载均衡。
![image](https://github.com/user-attachments/assets/b0d5d714-c6a2-4e9f-83fc-fe6fe3d0fa59)

### 请尽可能提供已有镜像站

与pypi共享相同的镜像站

**Comment by happy-game** [comment]
谢谢你给的资料, 我阅读了以下官方文档, 总结了一下实现该换源方式需要注意的部分:
1. `uv`使用多个配置文件, 包括系统级(`/etc/uv/uv.toml or $XDG_CONFIG_HOME/uv/uv.toml`), 用户级(`~/.config/uv/uv.toml or $XDG_CONFIG_HOME/uv/uv.toml`), 和项目级(`workspaces/pyproject.toml or uv.toml`), 以上目录为linux和macos.
2. windows 配置文件位于 `%APPDATA%\uv\uv.toml`(用户级)和`%SYSTEMDRIVE%\ProgramData\uv\uv.toml`
3. 项目级配置文件 `uv.toml`优先级大于`pyproject.toml`
4. 如果找到了多个配置文件(上面所述)， 那么它们会被合并, 优先级为 项目>用户>系统

需要进一步确认的部分：
1. 系统级和用户级都涉及了 `$XDG_CONFIG_HOME/uv/uv.toml`, 且优先级较高, 需要进一步确认有何区别
2. 项目级配置文件指的是什么

**Comment by happy-game** [comment]
我测试了一下最终的优先级顺序如下(高到低):

1. $workspaces/uv.toml($workspaces指使用 `uv init`创建的项目目录)
2. $workspaces/pyproject.toml
3. ~/.config/uv/uv.toml
4. /etc/uv/uv.toml

`$XDG_CONFIG_HOME/uv/uv.toml`中的设置不会生效.

**Comment by happy-game** [comment]
可以将该工作assign给我, 我预计会在接下来的几天实现该recipe.

**Comment by ccmywish** [comment]
@xyx1926885268 

已支持，可按README中所述下载安装最新版使用，若无问题，可随时关闭此issue
