### ISSUE TITLE
可以还原源设置吗

### ISSUE THREAD

**Issue by zyxun** [RubyMetric/chsrc#14]

**Comment by ccmywish** [comment]
@zyxun 我考虑了一下，可能实现起来并不麻烦。可以实现一个 `chsrc reset` 的命令。

你是否有比较强的理由或者场景？我个人可能最近时间不多，能否考虑参与维护你所熟悉的一部分？

**Comment by ccmywish** [comment]
@zyxun 请问需要哪个软件的源？并请告诉我它的默认`url`是什么

**Comment by ccmywish** [comment]
@zyxun 

已添加新命令 `chsrc reset`. 目前仅支持这几个重置源，如果你需要其它的，需要你提供默认`url`
https://gitee.com/RubyMetric/chsrc/issues/I9V6EV

**Comment by ccmywish** [comment]
@zyxun 功能本身已完全完成，后续仅反馈新的可重置源即可。

支持情况：https://gitee.com/RubyMetric/chsrc/issues/I9V6EV
