### ISSUE TITLE
Rocky替换的源的代码中有错误，不适应Rocky Linux 9.5的使用

### ISSUE THREAD

**Issue by haneu123M** [RubyMetric/chsrc#149]
### 你操作了什么？

我在root用户运行了chsrc set rocky

### 发生了什么？

[chsrc 运行] sed -e 's|^mirrorlist=|#mirrorlist=|g' -e 's|^#baseurl=http://dl.rockylinux.org/$contentdir|baseurl=https://mirrors.sustech.edu.cn/rocky-linux|g' -i.bak /etc/yum.repos.d/Rocky-*.repo
sed：无法读取 /etc/yum.repos.d/Rocky-*.repo：没有那个文件或目录
[chsrc 运行] x 命令执行失败，退出状态: 512
chsrc: 关键错误，强制结束

### 本应该怎么样？

sed -e 's|^mirrorlist=|#mirrorlist=|g' -e 's|^#baseurl=http://dl.rockylinux.org/$contentdir|baseurl=https://mirrors.sustech.edu.cn/rocky-linux|g' -i.bak /etc/yum.repos.d/Rocky-*.repo
改成
sed -e 's|^mirrorlist=|#mirrorlist=|g' -e 's|^#baseurl=http://dl.rockylinux.org/$contentdir|baseurl=https://mirrors.sustech.edu.cn/rocky-linux|g' -i.bak /etc/yum.repos.d/rocky*.repo
后，成功换源

### chsrc 版本

chsrc: Change Source (GPLv3+) v0.1.9.5-2024/12/06 by RubyMetric

### 你使用的是哪个操作系统？

Linux

### OS 版本 / OS 发行版

Rocky Linux 9.5(Blue Onyx)

### Log 输出

```shell
[chsrc 测速] 测速中

  x 上游默认源 默认上游源URL未知，请帮助补充
  x MirrorZ 校园网镜像站 功能特殊无法测速，跳过
  - 阿里巴巴开源镜像站(公网) ... 483.91 KByte/s
  - 火山引擎开源软件镜像站(公网) ... 1.20 MByte/s
  - 上海交通大学致远镜像站 ... 220.00 KByte/s
  - 南方科技大学开源软件镜像站 ... 18.30 MByte/s
  - 浙江大学开源软件镜像站 ... 9.76 MByte/s
  - 兰州大学开源社区镜像站 ... 8.67 MByte/s
  - 搜狐开源镜像站 ... 3.94 KByte/s
  - 网易开源镜像站 ... 30.57 KByte/s

最快镜像站: 南方科技大学开源软件镜像站
选中镜像站: SUSTech (sustech)
--------------------------------
[chsrc 运行] sed -e 's|^mirrorlist=|#mirrorlist=|g' -e 's|^#baseurl=http://dl.rockylinux.org/$contentdir|baseurl=https://mirrors.sustech.edu.cn/rocky-linux|g' -i.bak /etc/yum.repos.d/Rocky-*.repo
sed：无法读取 /etc/yum.repos.d/Rocky-*.repo：没有那个文件或目录
[chsrc 运行] x 命令执行失败，退出状态: 512
```

### 防止重复问题

- [X] 我已在项目的 GitHub 和 Gitee 两个仓库分别搜索过类似的 issue

**Comment by ccmywish** [comment]
@haneu123M  感谢报告

看代码换源逻辑没有问题，https://github.com/RubyMetric/chsrc/blob/main/src/recipe/os/YUM/Rocky-Linux.c

怀疑是检查版本的位置错了，请帮忙在命令行上运行下这个命令，看看结果是否是 `9.5`
```bash
sed -nr 's/ROCKY_SUPPORT_PRODUCT_VERSION=(.*)/\1/p
```

**Comment by haneu123M** [comment]
在运行了上述的sed命令以后，显示的结果如下
```Linux
[root@localhost bin]# sed -nr 's/ROCKY_SUPPORT_PRODUCT_VERSION=(.*)/\1/p
> 
```

看了一下源代码，可能需要运行的命令是
```Linux
sed -nr 's/ROCKY_SUPPORT_PRODUCT_VERSION=(.*)/\\1/p'
```
但是结果如下
```Linux
[root@localhost bin]# sed -nr 's/ROCKY_SUPPORT_PRODUCT_VERSION=(.*)/\\1/p'

```
是的，命令行并没有显示任何的结果，只出现了一个空的行

**Comment by happy-game** [comment]
此处实际运行的命令是:
```
sed -nr 's/ROCKY_SUPPORT_PRODUCT_VERSION=(.*)/\1/p' /etc/os-release 
```
输出结果是
```
"9.x"
```
我们需要的是引号内的内容, 不应该包含引号, 所以正确的命令应该是:
```
sed -nr 's/ROCKY_SUPPORT_PRODUCT_VERSION="(.*)"/\1/p' /etc/os-release 
```
这样输出结果就是
```
9.x
```

**Comment by ccmywish** [comment]
那就和 #110 这里的问题一样，多了双引号，我来改一下

**Comment by ccmywish** [comment]
@happy-game 

要不你来改吧，顺便看下你的写权限是否生效，顺便检测下你能否关 PR

```c
  version_str = xy_str_delete_prefix (version_str, "\"");
  version_str = xy_str_delete_suffix (version_str, "\"");
```

**Comment by ccmywish** [comment]
@haneu123M 

已修复，可按README中所述下载安装最新版使用，若无问题，可随时关闭此issue
