### ISSUE TITLE
添加 set `all [optional]<os|lang|ware>` 命令

### ISSUE THREAD

**Issue by baka-gourd** [RubyMetric/chsrc#15]
这条命令能够极大的方便大量环境的初始化配置，而不用一个一个打

使用场景：

- pacstrap 一整个环境后运行
- 非持久化临时移动开发环境快速配置
- etc...

**Comment by ccmywish** [comment]
你好 @baka-gourd 

我理解你的意思。我的顾虑是，不同开发场景需要的软件栈都非常不同，没有办法预料到你需要换哪些软件。

我时常也想要一键完全换源，一键setup，但是用户的场景太过不同。我觉得用户可以直接写一个小的 shell脚本 `for` 循环来 `chsrc` 一下即可

**Comment by ccmywish** [comment]
@baka-gourd 如果你有更好的理由或者觉得实现非常容易，我愿意接着考虑实现它

另外，你应该使用`arch linux`，是否有兴趣将 `chsrc` 添加至 AUR？

**Comment by baka-gourd** [comment]
的确每个人的技术栈都不尽相同，但是我觉得一次更换在大部分情况下是符合人们需求的。实现起来也只是针对每一分类进行一次`for`循环，因为检测相关软件的存在与否是已经实现了的。的确，自己写一个shell脚本能够解决这个比较私人的问题，我会关闭这个 issue。

关于AUR的问题，我认为使用 Action 自动化发布是更好的选择。我并不是能够想起来及时更新上传软件包的人🥲相关链接已在 #16 提及
