### ISSUE TITLE
openwrt 换源失败 `cp` 不存在备份选项

### ISSUE THREAD

**Issue by happy-game** [RubyMetric/chsrc#152]
### 你操作了什么？

chsrc set openwrt

### 发生了什么？

换源过程中的备份文件失败, 因为`openwrt`版的`cp`不支持` backup=t`

### 本应该怎么样？

我希望能够成功换源

### chsrc 版本

v0.1.9.6-2024/12/13

### 你使用的是哪个操作系统？

Linux

### OS 版本 / OS 发行版

openwrt x86_64

### Log 输出

```shell
/ # /usr/local/bin/chsrc set openwrt
[chsrc 测速] 测速中

  x 上游默认源 上游默认源不测速
  x MirrorZ 校园网镜像站 功能特殊无法测速，跳过
  - 阿里巴巴开源镜像站(公网) ... 475.92 KByte/s
  - 腾讯软件源(公网) ... 121.00 KByte/s
  - 清华大学开源软件镜像站 ... 7.19 MByte/s
  - 上海交通大学致远镜像站 ... 0.00 Byte/s | HTTP码 000
  - 中国科学技术大学开源镜像站 ... 24.91 MByte/s
  - 北京大学开源镜像站 ... 13.63 MByte/s
  - 南方科技大学开源软件镜像站 ... 32.36 MByte/s

最快镜像站: 南方科技大学开源软件镜像站
选中镜像站: SUSTech (sustech)
--------------------------------
cp: unrecognized option: backup=t
BusyBox v1.35.0 (2023-03-09 00:52:47 UTC) multi-call binary.

Usage: cp [-arPLHpfinlsTu] SOURCE DEST
or: cp [-arPLHpfinlsu] SOURCE... { -t DIRECTORY | DIRECTORY }

Copy SOURCEs to DEST

        -a      Same as -dpR
        -R,-r   Recurse
        -d,-P   Preserve symlinks (default if -R)
        -L      Follow all symlinks
        -H      Follow symlinks on command line
        -p      Preserve file attributes if possible
        -f      Overwrite
        -i      Prompt before overwrite
        -n      Don't overwrite
        -l,-s   Create (sym)links
        -T      Refuse to copy if DEST is a directory
        -t DIR  Copy all SOURCEs into DIR
        -u      Copy only newer files
[chsrc 运行] x 命令执行失败，退出状态: 256
chsrc: 关键错误，强制结束
```

### 防止重复问题

- [X] 我已在项目的 GitHub 和 Gitee 两个仓库分别搜索过类似的 issue

**Comment by happy-game** [comment]
看输出好像我的`cp`命令是来自`busybox`, 跟常规的发行版不太一样, 可能其他基于`busybox`构建的系统也会有这个问题.

感觉可以在备份失败以后提示用户输入`y/N`来选择是否使用不带`backup=t`的`cp`或者直接覆盖文件.

**Comment by ccmywish** [comment]
https://github.com/RubyMetric/chsrc/commit/252a64924fab5d53a6ee5d3ba8f3dbc497266c0a

> 备份失败以后提示用户输入y/N

咱们能避免用户手动输入就尽量避免，现在改成检测是否为 GNU 的 `cp` 了，可以试一下能不能工作。

另外 openwrt 本身换源方案可能有问题，如果这个问题解决了，但是 openwrt 还是换不了，就再开一个 issue.

**Comment by happy-game** [comment]
修改后依旧无法换源成功, 此外经测试在其他系统(至少是`archlinux`)上也无法换源成功.

问题在
https://github.com/RubyMetric/chsrc/blob/252a64924fab5d53a6ee5d3ba8f3dbc497266c0a/src/framework/core.c#L1291

在此处会触发段错误, 我测了一下发现这里运行的指令是`cp --version 1>/dev/null 2>&1`, 输出结果是空字符串, 导致在https://github.com/RubyMetric/chsrc/blob/6ded3380e5f475760cfdadd39f898a8ab6dcfc9f/include/xy.h#L625
处直接跳出, 此时`ret`还是NULL. 我认为这里要多做一下处理, 获取版本的指令也应该做一点修改.

另外 `busybox cp`的没有 `--version`, 具体输出如下:
```
cp: unrecognized option: version
BusyBox v1.36.1 (2024-02-20 20:57:25 UTC) multi-call binary.

Usage: cp [-arPLHpfinlsTu] SOURCE DEST
or: cp [-arPLHpfinlsu] SOURCE... { -t DIRECTORY | DIRECTORY }

Copy SOURCEs to DEST

        -a      Same as -dpR
        -R,-r   Recurse
        -d,-P   Preserve symlinks (default if -R)
        -L      Follow all symlinks
        -H      Follow symlinks on command line
        -p      Preserve file attributes if possible
        -f      Overwrite
        -i      Prompt before overwrite
        -n      Don't overwrite
        -l,-s   Create (sym)links
        -T      Refuse to copy if DEST is a directory
        -t DIR  Copy all SOURCEs into DIR
        -u      Copy only newer files
```
这条指令在运行的时候是属于异常退出, 返回值是 `1`

**Comment by ccmywish** [comment]
把`stderr`转到`stdout`后，依然利用上述的判断条件判断是否为 `GNU cp`，我在我自己环境试了一下应该没问题了，你可以再试一下 🤝

 https://github.com/RubyMetric/chsrc/commit/d4ab7e0ec605d585190e93f7dfae821913a609ae

**Comment by happy-game** [comment]
> 把`stderr`转到`stdout`后，依然利用上述的判断条件判断是否为 `GNU cp`，我在我自己环境试了一下应该没问题了，你可以再试一下 🤝
> 
> [d4ab7e0](https://github.com/RubyMetric/chsrc/commit/d4ab7e0ec605d585190e93f7dfae821913a609ae)

cp 的问题解决了, 但是openwrt依旧有问题, 我会新开一个issue.
