### ISSUE TITLE
PR 模板的 front matter

### ISSUE THREAD

**Issue by ccmywish** [RubyMetric/chsrc#158]
在我们的模板中有这么一些内容：https://github.com/RubyMetric/chsrc/blob/main/.github/pull_request_template.md?plain=1#L1-L7

会导致这样的效果：

![image](https://github.com/user-attachments/assets/635a9666-d67a-403a-8b0c-d60a0ce003cd)

**Comment by ccmywish** [comment]
@wickdynex 

What does this code do? Can we fix it?

**Comment by happy-game** [comment]
These contents are manually filled in by me. I am uncertain as to what content will be automatically formatted and I am slightly puzzled by this.

**Comment by wickdynex** [comment]
Hi @ccmywish ,
I'm sorry about that. After referring to the official doc [Creating a pull request template for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository), the `PR template` can only display the content in a new PR without other useful features which is different from `Issue Template`.
So, it's a little bit confused to see that. Anyway, if u like, I'll remove and fix it personally later.
Sorry about that honestly.

**Comment by wickdynex** [comment]
> @wickdynex
> 
> No need to say sorry. It's OK, no one knows all the details of a thing. 😊
> 
> I think **it's not a mistake, it's a sound reasoning from `Issue Template` to expect `PR template` to behave the same way.**
> 
> We all learn by tries and mistakes. Let go of the burden, be bold to act. 👍

I feel so impressed with your mercy also encouragement. Now this issue is fixed correctly, thanks for your patience🥰.

**Comment by ccmywish** [comment]
Thanks!

**Comment by wickdynex** [comment]
> Thanks!

🥳welcome
