### ISSUE TITLE
是否考虑支持更换docker源

### ISSUE THREAD

**Issue by kaizh102** [RubyMetric/chsrc#25]
是否考虑支持更换docker源？

**Comment by ccmywish** [comment]
@kaizh102 你好，Gitee已有该issue：https://gitee.com/RubyMetric/chsrc/issues/I80UDD

本来考虑下一版本`v0.1.6`支持，但是似乎目前国内的docker hub镜像都挂了

**Comment by ccmywish** [comment]
@kaizh102 @xialaup 

已于`v0.1.6`添加对`dockerhub`的支持，但是目前没有任何可用源，可下载试用最新版体验其他功能。
