### ISSUE TITLE
consider marking 0.1.5 tag as latest release

### ISSUE THREAD

**Issue by chenrui333** [RubyMetric/chsrc#27]
👋 looks like 0.1.5 tag is not the latest, consider mark it as latest and remove the latest tag (which is kind of outdated)

![image](https://github.com/RubyMetric/chsrc/assets/1580956/bbdaaeb3-5c51-4d6a-bb32-f0e97113ea24)

relates to https://github.com/Homebrew/homebrew-core/pull/173951

**Comment by ccmywish** [comment]
Hi @chenrui333 

I've released the newest version `v0.1.6`.

----

Do I have to remove the tag 'latest'? In fact, I'm still using it to provide (in GitHub actions) a stable url for users to always download the real latest precompiled binaries. That means, 
1. the **binaries** in `latest` release and in `v0.1.6` release are just the totally same. 
2. However, the **source code** in two releases are not the same, the code in `latest` release is surely obsolete as you think.

https://github.com/RubyMetric/chsrc/blob/main/.github/workflows/linux-x64.yml#L23-L30

So could you please give me some advice based on your abundant experiences? Is there any best practice? Or it just doesn't matter?

**Comment by ccmywish** [comment]
I'm wondering how `homebrew` work to check updating.

Now the repo has two `latest`:

1. tag name `v0.1.6`: I've set it to **`Latest`** via GitHub page
![image](https://github.com/RubyMetric/chsrc/assets/63459097/70a940d6-4a5c-41c7-9091-62b4e6563558)

2. tag name `latest`，it's just a name which I used `git tag` to generate.

<br>

So which one will `homebrew` consider?

**Comment by chenrui333** [comment]
> Do I have to remove the `tag latest`? In fact, I'm still using it to provide (in GitHub actions) a stable url for users to always download the real latest precompiled binaries.

what you should do is probably like what folks are doing with github actions, so that v1 would be a alias tag to all v1 releases.

because the latest approach would be dangerous for v2 v3 breaking releases. 

what do you think?

**Comment by ccmywish** [comment]
Thank you for pointing out the breaking issue.

Although I don't think this command line tool's interface will change, I still appreciate the idea. 

I will rename the `tag latest` to another name like `prebuilt` or something.

**Comment by ccmywish** [comment]
Rename to `tag pre`, and set it to `Pre-release`
