### ISSUE TITLE
MacOS版本在x64的mac上执行显示bad cpu type

### ISSUE THREAD

**Issue by klx1204** [RubyMetric/chsrc#28]
是否MacOS的x64版本是arm架构用的？现在并没有提供x64版本？

<img width="850" alt="截屏2024-06-08 上午11 45 40" src="https://github.com/RubyMetric/chsrc/assets/51480563/470501c1-09bf-4846-a435-c1ffa8b05a7a">

**Comment by ccmywish** [comment]
@klx1204  感谢反馈！

是的，我刚才才发现 `macos-latest` 现在已经用的是M1了.

我刚发布了 `v0.1.6`，现在`x64`和`M1`都支持了，可在README里寻找最新版下载链接。试用如果无问题，请关闭此issue，谢谢！

**Comment by klx1204** [comment]
@ccmywish 验证可用，感谢！
