### ISSUE TITLE
提供一些源，仅供参考。

### ISSUE THREAD

**Issue by weiyidu** [RubyMetric/chsrc#32]
之前使用这个方法换源，不过他的没有测速。
https://linuxmirrors.cn/mirrors/

**Comment by ccmywish** [comment]
谢谢，对于还没有实现的换源，可能会参考一下这个

**Comment by ccbikai** [comment]
https://mirrors.help

再补充一些

**Comment by ccmywish** [comment]
@ccbikai 感谢支持。`chsrc` 最开始实现的时候，就从 MirroZ 项目中收益许多，见致谢。

但是我还是第一次见这个域名，谢谢你让我知道。

**Comment by zheng7fu2** [comment]
Arch Linux CN Community repo mirrors list
https://github.com/archlinuxcn/mirrorlist-repo

archlinuxcn仓库可以单独换源吗？

**Comment by ccmywish** [comment]
你好，@zheng7fu2 

你的意思是除了 `chsrc set archlinux`，再额外加一个 `chsrc set archlinuxcn` 吗？

**Comment by zheng7fu2** [comment]
是的，因为 archlinuxcn仓库 不是 Arch Linux官方的软件仓库。

**Comment by ccmywish** [comment]
@zheng7fu2 

我的意思是，现在 `chsrc set archlinux` 的时候，会直接也把 `archlinuxcn` 也给换了。

你是有需求把它们两个使用不同的源吗？

**Comment by zheng7fu2** [comment]
@ccmywish 是的。
希望archlinux的仓库由Reflector 根据规则自动更新镜像源。
但是Archlinuxcn的仓库可以由chsrc来指定镜像源。

**Comment by ccmywish** [comment]
@zheng7fu2 你好，

基于你的建议，我已将 arch 和 archlinuxcn 拆分为了两个不同的源，可以分别使用：
```bash
chsrc set arch

chsrc set archlinuxcn
```
我刚已发布了最新版，可以从README链接中下载试用。

**Comment by fortystory** [comment]
rust有个字节的源 https://rsproxy.cn/

**Comment by ccmywish** [comment]
@fortystory 

感谢你提供的信息 👍 请参考 https://github.com/RubyMetric/chsrc/issues/68
