### ISSUE TITLE
Windows 中文显示问题

### ISSUE THREAD

**Issue by lixxu** [RubyMetric/chsrc#36]
![图片](https://github.com/RubyMetric/chsrc/assets/264487/b10119af-6778-46ab-84b9-f8b286c91eb5)

windows11, powershell终端, 集成了starship

**Comment by ccmywish** [comment]
你好，@lixxu 

还没遇到过这种情况。上图中是第二次运行时有问题。所以，是每次打开终端后，第二次运行`chsrc`才有问题吗？

**Comment by lixxu** [comment]
不是, 运行`chsrc get py`时每次都有问题, 其它的貌似没问题.
![图片](https://github.com/RubyMetric/chsrc/assets/264487/1587a0b7-2cd2-4bbd-b3b7-fc27d707fa5e)

**Comment by ccmywish** [comment]
我这边配置跟你一样的，也是 windows11 + powershell + starship

![image](https://github.com/RubyMetric/chsrc/assets/63459097/a6ce8baf-6cdd-48b8-989d-7be046b7c61e)

应该是你的 python3 的输出导致 `chsrc` 乱码了。你看下你的 `python3` 命令的
1. 版本
2. 如何安装的
3. 以及默认输出编码（可能是其他字符集）

**Comment by ccmywish** [comment]
你的 `python3` 确认是和 `python` 相同吗？

**Comment by ccmywish** [comment]
1. 你用 `Get-Command python` 和   `Get-Command python3` 分别看下

2. 我恰巧开发了 `rbenv-for-Windows`，所以我怀疑 `pyenv` 是导致问题的原因。 `pyenv` 如果我没记错，是按着 `rbenv` 实现的。所以你看下 `pyenv` 管理下的 `python3` 命令是 `.bat` 还是 `.exe` ？ 我怀疑可能是 `pyenv` 的存在导致第一层编码是 GBK，然后才是你Python3的编码UTF-8

**Comment by lixxu** [comment]
是的, 确实是.bat导致的.
![图片](https://github.com/RubyMetric/chsrc/assets/264487/bad3a39a-8f7a-4e23-adf8-226bb123d671)
![图片](https://github.com/RubyMetric/chsrc/assets/264487/738d2662-7865-45bc-a4d6-8d87a9e0175b)

**Comment by ccmywish** [comment]
不知道 `pyenv` 为啥要设置为 `1250`. [rbenv-for-windows](https://github.com/ccmywish/rbenv-for-windows) 的实现就完全没有这个问题。 

![image](https://github.com/RubyMetric/chsrc/assets/63459097/6ec1bdc7-e313-4e18-8694-ccb925f9d6b1)

可以联系 `pyenv-win` 询问一下原因，以及解决方法。

**Comment by lixxu** [comment]
ok, 我尝试把python.bat, python3.bat, python3.11.bat, pip.bat都改成了utf-8, 仍然不起作用. 我去pyenv那边看看, 谢谢解惑.
![图片](https://github.com/RubyMetric/chsrc/assets/264487/771adb2a-8213-46b0-8835-d047730525a1)

**Comment by lixxu** [comment]
把pyenv.bat里的编码改成utf-8就可以了, issue可以关了.
![图片](https://github.com/RubyMetric/chsrc/assets/264487/18d5e6d1-f2c7-4b2b-986d-07f1c1aeb442)
![图片](https://github.com/RubyMetric/chsrc/assets/264487/53c4fadf-8d43-4263-91ad-c8b792d784e5)

**Comment by ccmywish** [comment]
恭喜终于解决了 💯 

`pyenv.bat` 里咋还有一个 `chcp` 呢，哈哈。若以后你知道为什么，可以在这里留言，我也学习了解一下。

**Comment by lixxu** [comment]
我看到pyenv-win里的issue有人在讨论chcp这个问题才去试一下, 应该和这个issue有关.
[https://github.com/pyenv-win/pyenv-win/issues/344](url)
