### ISSUE TITLE
Add os armbian

### ISSUE THREAD

**Issue by livelycode36** [RubyMetric/chsrc#37]
没撸过C，根据commit记录改的，不知道是否标准

**环境**
- OS：ArmBian
- Version：[Armbian_bookworm_save_2024.06](https://github.com/ophub/amlogic-s9xxx-armbian)
- 机器：panther-x2

**功能**
- 增加了对armbian的支持

**测试**
在机器上，编译测试通过
![image](https://github.com/RubyMetric/chsrc/assets/57926220/4f42d1b0-2272-4ff4-9b74-ea75e0d10d5c)

**Comment by ccmywish** [comment]
已完成 By @livelycode36
