### ISSUE TITLE
连续两次更换 ubuntu 的源会导致添加出错

### ISSUE THREAD

**Issue by JAM2199562** [RubyMetric/chsrc#40]
假设原来的源是
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble main restricted universe multiverse
要添加的源是 https://mirrors.internal.local/nexus/repository/ubuntu22.04
执行的命令是
`chsrc set ubuntu https://mirrors.internal.local/nexus/repository/ubuntu22.04`
首次执行后，可以成功使用
但是假设我记错了发行版，现在需要进行修复，执行的命令如下
`chsrc set ubuntu https://mirrors.internal.local/nexus/repository/ubuntu24.04`
之后 apt update 就会出错了
查看 sourcelist.list，发现源变成了了下面这样
https://mirrors.internal.local/nexus/repository/ubuntu22.04/24.04
如果多次执行，这行就会一直变长

**Comment by ccmywish** [comment]
你好 @JAM2199562 

是的，按照现有的代码，确实会出现你所说的现象。但是这是跟你指定的URL相关的。

目前所有公开的Ubuntu的换源URL都是类似下图这样的，各大镜像站都不会指定后面的ubuntu具体版本数字

![image](https://github.com/RubyMetric/chsrc/assets/63459097/4181c730-626d-41f8-b0a2-91f5ddc5a336)

你可以看下 https://mirrors.aliyun.com/ubuntu/ 的目录结构。

所以上述你提供的似乎是内部专用的Ubuntu源，该源是否搭建有问题？

**Comment by ccmywish** [comment]
@JAM2199562 

我明白。所以你那边可以修改URL从而不指定后面的版本号吗？

如果不能，有什么困难吗？如果困难很大，我这边可以调整代码。

**Comment by JAM2199562** [comment]
> @JAM2199562
> 
> 我明白。所以你那边可以修改URL从而不带后面的版本号吗？
> 
> 如果不能，有什么困难吗？如果困难很大，我这边可以调整`chsrc`的代码。

明白，我这边确实是可以改的，而且最简单的办法就是我不执行两次就行啦，所以这个也就是反馈一下，倒也不用您一定修改代码。谢谢！

**Comment by ccmywish** [comment]
感谢理解👍
