### ISSUE TITLE
debian换源异常

### ISSUE THREAD

**Issue by Tom722** [RubyMetric/chsrc#43]
./chsrc set debian bfsu

[chsrc 检查] √ 文件 /etc/apt/sources.list.d/debian.sources 存在
[chsrc 提示] 将基于新格式换源
选中镜像站: BFSU (bfsu)
--------------------------------
[chsrc 提示] 如果遇到无法拉取 HTTPS 源的情况，我们会使用 HTTP 源并需要您运行:
apt install apt-transport-https ca-certificates
[chsrc 运行] cp /etc/apt/sources.list.d/debian.sources /etc/apt/sources.list.d/debian.sources.bak --backup='t'
[chsrc 运行] 命令执行成功
[chsrc 提示] 备份文件名为 /etc/apt/sources.list.d/debian.sources.bak
[chsrc 运行] sed -E -i 's@https?://.*/debian/?@https://mirrors.bfsu.edu.cn/debian@g' /etc/apt/sources.list.d/debian.sources
[chsrc 运行] 命令执行成功

[chsrc 运行] sed -E -i 's@https?://.*/debian-security/?@https://mirrors.bfsu.edu.cn/debian-security
sh: 1: Syntax error: Unterminated quoted string
[chsrc 运行] 命令执行失败，返回码 512
chsrc: 关键错误，强制结束

**Comment by ccmywish** [comment]
你好，@Tom722

问题已修复，可重新试用README中的链接下载最新版。无论对或错，都请麻烦把整个运行效果再如上贴出来，方便我再检查一下执行流程。

若无问题，可关闭该issue

**Comment by Tom722** [comment]
运行效果如下：

./chsrc set debian tencent

[chsrc 检查] √ 文件 /etc/apt/sources.list.d/debian.sources 存在
[chsrc 提示] 将基于新格式换源
选中镜像站: Tencent (tencent)
--------------------------------
[chsrc 提示] 如果遇到无法拉取 HTTPS 源的情况，我们会使用 HTTP 源并需要您运行:
apt install apt-transport-https ca-certificates
[chsrc 运行] cp /etc/apt/sources.list.d/debian.sources /etc/apt/sources.list.d/debian.sources.bak --backup='t'
[chsrc 提示] 备份文件名为 /etc/apt/sources.list.d/debian.sources.bak
[chsrc 运行] sed -E -i 's@https?://.*/debian/?@https://mirrors.tencent.com/debian@g' /etc/apt/sources.list.d/debian.sources
[chsrc 运行] 命令执行成功

[chsrc 运行] sed -E -i 's@https?://.*/debian-security/?@https://mirrors.tencent.com/debian-security@g' /etc/apt/sources.list.d/debian.sources
[chsrc 运行] 命令执行成功

[chsrc 运行] apt update
Get:1 https://mirrors.tencent.com/debian bookworm InRelease [151 kB]
Get:2 https://mirrors.tencent.com/debian bookworm-updates InRelease [55.4 kB]
Get:3 https://mirrors.tencent.com/debian-security bookworm-security InRelease [48.0 kB]
Get:4 https://mirrors.tencent.com/debian bookworm/main amd64 Packages [8788 kB]
Get:5 https://mirrors.tencent.com/debian bookworm-updates/main amd64 Packages [13.8 kB]
Get:6 https://mirrors.tencent.com/debian-security bookworm-security/main amd64 Packages [168 kB]
Fetched 9224 kB in 3s (2942 kB/s)               
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
4 packages can be upgraded. Run 'apt list --upgradable' to see them.
[chsrc 运行] 命令执行成功
--------------------------------
chsrc: 全自动换源完成，感谢镜像提供方: 腾讯软件源
