### ISSUE TITLE
Homebrew换源前不检查.zshrc是否存在

### ISSUE THREAD

**Issue by NewbieXvwu** [RubyMetric/chsrc#47]
% chsrc set brew
[chsrc 检查] √ 命令 curl 存在
测速 https://mirrors.tuna.tsinghua.edu.cn/ ... 46.78 MByte/s
测速 https://mirrors.bfsu.edu.cn/ ... 87.46 MByte/s
测速 https://mirrors.zju.edu.cn/ ... 12.11 MByte/s
测速 https://mirrors.sustech.edu.cn/ ... 54.87 MByte/s
最快镜像站: 北京外国语大学开源软件镜像站
选中镜像站: BFSU (bfsu)
--------------------------------
[chsrc 运行] cp -f ~/.zshrc ~/.zshrc.bak
cp: /Users/newbiexvwu/.zshrc: No such file or directory
[chsrc 运行] 命令执行失败，返回码 256
chsrc: 关键错误，强制结束

**Comment by ccmywish** [comment]
你好，你的macOS版本是多少？有 `~/.zprofile` 这个文件吗？

**Comment by NewbieXvwu** [comment]
版本是Sonoma 14.5 黑苹果，经检查没有~/.zprofile这个文件。我后来自己手动创建了一个空的.zshrc文件即可正常使用chsrc。提这个issue主要是希望程序在执行cp -f ~/.zshrc ~/.zshrc.bak这条命令前能先检查是否有.zshrc存在，如果没有就不执行该命令，直接往下执行。

**Comment by ccmywish** [comment]
@NewbieXvwu 

👍 感谢你的建议，文件不存在时将不再备份。已修改但还没有发布新版本。
