### ISSUE TITLE
希望添加 fish 终端支持

### ISSUE THREAD

**Issue by Word2VecT** [RubyMetric/chsrc#54]
某些换源方式比如 brew 是基于终端的，目前似乎仅支持 bash 与 zsh

**Comment by ccmywish** [comment]
@Word2Vect

你好，你说的是对的，对 Homebrew 换源目前就是通过写入环境变量到 profile 中实现。

抱歉我对 Fish shell 并不熟悉，也没有办法测试，但是理论上来看，提供支持并不复杂。你是否有兴趣提供支持？

https://github.com/RubyMetric/chsrc/blob/main/src/recipe/ware/Homebrew.c

若实现有困难，可以随时在 discussion 中询问任何问题：https://github.com/RubyMetric/chsrc/discussions/50

**Comment by Word2VecT** [comment]
我对此感兴趣，我将在这周内试试实现支持

**Comment by ccmywish** [comment]
Finished by #75
