### ISSUE TITLE
如何在线更新？更新源地址？

### ISSUE THREAD

**Issue by blank-1** [RubyMetric/chsrc#60]

**Comment by ccmywish** [comment]
@blank-1 感谢你的使用和反馈。

目前不支持在线更新源，源和软件是捆绑在一起的，可查看具体原因：https://github.com/RubyMetric/chsrc/issues/33

这就是为什么一直希望有人贡献给各个包管理器的原因，可以很方便的使用 `scoop update chsrc` 就可以更新了。

如果你遇到了什么特殊的需求，可以说明你的情况，以让我再衡量是否需要支持数据分离。如无其他问题，可关闭此issue.

**Comment by ccmywish** [comment]
@blank-1 

现在开始协作维护 Wiki：https://github.com/RubyMetric/chsrc/wiki

最终目标是 `chsrc` 完全按照 Wiki 的最新镜像状态来实现
