### ISSUE TITLE
能否在我的项目中集成该软件用来优化国内源

### ISSUE THREAD

**Issue by shencangsheng** [RubyMetric/chsrc#61]
这是我的项目 [easy-registry-mirror](https://github.com/shencangsheng/easy-registry-mirror)，用来搭建私有仓库，我希望使用chsrc来改进在不用代理时自动选择最快的国内源

**Comment by ccmywish** [comment]
@shencangsheng 

你好，感谢你的使用和认可 🤝。 `chsrc` 使用 `GPLv3+`，不知道你集成的方式是怎么样的？我将尽可能叙述各种情况，你可依据你自己的情况来作判断。

我觉得这也是一个好机会来表达我对 GPL 的理解，如果有任何疑问，可以询问更加专业的相关人士。

<br>

## 如果需要修改 `chsrc` 的源代码

`GPL` 要求你必须公开你的修改，既然你是一个开源项目，我觉得这不是什么问题。

问题在于：我看了下你使用的是MIT协议。如果你把 `chsrc` 修改后作为你整个软件的一部分提供，那么你的整个项目就会被传染为 `GPLv3+`。这意味着你需要重新把你的MIT协议修改成 `GPLv3+`

<br>

## 如果不修改 `chsrc` 源代码，但是编译了其中一部分进行链接

我看到你依赖一个你编写的 Rust 组件，不知道你会不会进行一些链接等操作。

如果是，同上，被传染为 `GPLv3+`

<br>

## 如果不修改 `chsrc` 源代码，仅仅使用二进制文件

1. 如果直接把二进制文件放到了你的项目（如压缩包里），仅需要额外给最终用户提供在本仓库的两份许可协议 `COPYING` 和 `LICENSE-MIT`

2. 如果并没有，只是从网上我提供的各个渠道下载 `chsrc`，则不需要做任何事情

<br>

作为 `chsrc` 的原作者之一，我希望 `chsrc` 得到广泛的运用，但是由于选择了 `GPL`，就依然要尽可能遵循 `GPL` 的法律要求。

**Comment by shencangsheng** [comment]
@ccmywish 

非常感谢，我目前的想法是仅仅使用二进制文件，作为一个工具，在部署 npm、Maven、PyPI 等仓库时，在未启用代理时，调用`chsrc` 选用一个目前速度最快的仓库，我目前使用的是默认的源，当前 Dockerhub 必须应用代理才可以正常使用，但其他仓库目前是并非需要代理才可以使用，当我看到`chsrc`觉得可以帮助选用更好的源。

当然我需要继续探索一下如何比较好的集成在我的项目里。

**Comment by shencangsheng** [comment]
@ccmywish 

你好，能否增加一个参数，仅输出当终端最快的源/first源嘛，或者我可以直接贡献这个功能吗

**Comment by ccmywish** [comment]
@shencangsheng 

可以直接用 `chsrc ls ruby | sed -n '/----/{n;n;p}'`

![image](https://github.com/user-attachments/assets/ec4195bb-aaef-436f-baac-28bf501219ff)

![image](https://github.com/user-attachments/assets/5402c4be-41b7-4cf4-952b-5383be7192ac)

**Comment by shencangsheng** [comment]
@ccmywish  第二个是默认的 `chsrc set ruby first `使用的源嘛？ 
输出测试最快的源，我写了一个命令 `./chsrc measure -no-color ruby | grep '测速' | awk '{print $(NF-1), $(NF), $2}' | sort -k1 -nr | head -n 1 | awk '{print $3}'`， 但我会有一些担心，比如速度单位可能会导致一些问题

**Comment by ccmywish** [comment]
最新版（还没有发布）的输出为了美观已经调整成下面这样了：

![image](https://github.com/user-attachments/assets/cd935518-8e50-4051-ad89-603f65fc6c6e)

前面是两个空格+ `- ` 下面是相关代码：

https://github.com/RubyMetric/chsrc/blob/main/include/chsrc.h#L538C1-L540

**Comment by shencangsheng** [comment]
@ccmywish 
我提交了一个 PR 给项目，在输出最快镜像站时，最后添加 site，不知道是否可以，下面是我的PR：
https://github.com/RubyMetric/chsrc/pull/71

预期效果
```
- 阿里巴巴开源镜像站 ... 10.54 MByte/s
- 腾讯软件源 ... 8.85 MByte/s

最快镜像站：阿里巴巴开源镜像站 - https://maven.aliyun.com/repository/public/
```

**Comment by ccmywish** [comment]
已完成。

## Wiki 页

以后可持续关注下面的 Java 镜像站状态信息Wiki 页。因为我不怎么用Java，所以可能需要时长有人维护这些东西。如果有空可以参与维护。

最终 `chsrc` 的目标会完全按照 Wiki 页来添加源。目前对 Ruby 的换源就是这样做的。

1. https://github.com/RubyMetric/chsrc/discussions/72
2. https://github.com/RubyMetric/chsrc/wiki/Ruby-MirrorSite

<br>

## 稳定的测速链接

我之后还想改进测速逻辑，目前是直接拿镜像站本身去测速，比如虽然我测的是 华为云镜像站提供的 Maven 源速度，但是这个测速实际上是去测了华为与镜像站一个Debian ISO这个大文件的速度来代替，也就是说，测速的结果，实际上跟 Maven 源没有什么直接关系。

这么做的原因是我找不到 Maven 某个可用包的稳定URL，而且这个包最好在 20MB 以上。若你知道这个，或有心帮忙查找，我将非常感谢，并且我们也将获得更加真实有意义的测速数据。

**Comment by shencangsheng** [comment]
@ccmywish 

我比较常用的 `Maven` 包中，应该是跟 `Hadoop` 相关的包会比较大，我找到一个  [Spark](https://mvnrepository.com/artifact/org.apache.spark/spark-core_2.13/3.5.2) 大概在 15M，不知道是否对你有用

**Comment by ccmywish** [comment]
感谢你花时间寻找 👍

我感觉大小有点偏小，因为有的人的下载速度非常快，15MB可能1~2秒就下载完了，这样测速的结果不太稳定。比如 RubyChina  镜像站给了一个 9.9MB 的文件，每次测速，我这边测得值都非常不稳定，很影响结果。

我顺着你给的链接又找了一圈，我也没有找到比 Spark 更大的了。就还是先用镜像站的大文件顶替着吧。

---

最后想问一下，Maven 上游原地址是什么？是 https://repo1.maven.org/maven2 这个吗？

我想要支持 `chsrc reset java`:

https://github.com/RubyMetric/chsrc/blob/main/src/recipe/lang/Java.c#L16
