### ISSUE TITLE
Ruby USTC 镜像站

### ISSUE THREAD

**Issue by ccmywish** [RubyMetric/chsrc#64]
原问题：https://ruby-china.org/topics/43331

镜像站信息：见 GitHub Discussions https://github.com/RubyMetric/chsrc/discussions/62

**Comment by ccmywish** [comment]
@ibug

感谢你在 RubyGems 镜像上所投入的大量时间和精力 👍 我已添加你们的 USTC 镜像站。

此后Ruby相关的镜像站讨论可在这里： 
1. https://github.com/RubyMetric/chsrc/wiki/Ruby-MirrorSite
2. https://github.com/RubyMetric/chsrc/discussions/62

**Comment by iBug** [comment]
请问您是否可以帮助实现 rubygems/rubygems-mirror#80 所述的功能？如果该功能实现了，多所其他教育网镜像站也可以很快解决 RubyGems / Bundler 的功能问题，毕竟大家都在用 `gem mirror` 同步 RubyGems 镜像。

**Comment by ccmywish** [comment]
@iBug 

最近时间比较紧，有空的时候我会看一下 🤝
