### ISSUE TITLE
Windows下 执行 chsrc set winget 时，会在当前目录下生成一个nul文件

### ISSUE THREAD

**Issue by anaer** [RubyMetric/chsrc#65]
应该是测速命令生成的, 可以自动删除不, 或者指定生成到%temp%目录下?

**Comment by ccmywish** [comment]
@anaer 

你好，感谢反馈。之前我自己也遇到了这个问题，但是后来一直都复现不了了。

这个问题只跟 Windows 有关，跟具体哪一个 target （无论是 winget 还是其它的）无关。

应该跟 `MSYS2` 或相关的环境有关。

能否提供具体的复现步骤？

**Comment by anaer** [comment]
![图片](https://github.com/user-attachments/assets/5e516df6-9cea-41c5-b81e-b21c02855de8)
是curl的输出文件

**Comment by ccmywish** [comment]
@anaer 

你好，这个 `nul` 文件是没有问题的。本来就是为了输出到这个空文件。

我测试过：

1. PowerShell，直接 `curl www.baidu.com -o nul`
2. CMD，直接 `curl www.baidu.com -o nul`
3. MSYS2，直接 `curl www.baidu.com -o nul`

都不会产生 `nul` 文件。

所以我还是不清楚你是怎么触发的？在我之前的触发案例里，是由于使用了其它脚本额外调用才意外产生的，你可以详细叙述你的环境。能够确定100%复现吗？

**Comment by anaer** [comment]
测试了下，大致知道原因了, 用的cmder+cygwin，curl版本是curl 8.8.0 (x86_64-pc-cygwin)
执行`curl www.baidu.com -o nul`会生成nul文件

使用系统自带的版本 curl 8.7.1 (Windows) , 是没有问题

**Comment by ccmywish** [comment]
@anaer 

刚发的 `v0.1.8.2` 已包含对 `Cygwin` 中 `curl` 特殊情况的支持，邀请你测试使用 🤝

可使用 README 中的下载链接下载最新版试用。

**Comment by anaer** [comment]
试了新版的 已经解决了

**Comment by happy-game** [comment]
linux也会在当前目录产生一个nul文件，内容是
![图片](https://github.com/user-attachments/assets/ccbefac2-2fa5-4d98-82c2-280426f7cded)
我用的chsrc版本是`chsrc 0.1.9.2`.
这个问题可以很轻松地复现

**Comment by ccmywish** [comment]
@happy-game 

见 #114。

似乎这样的话，所有在Linux和macOS上运行 `chsrc` 都会产生该文件

有空提交一个修复吗？

**Comment by happy-game** [comment]
> @happy-game
> 
> 见 #114。
> 
> 似乎这样的话，所有在Linux和macOS上运行 `chsrc` 都会产生该文件
> 
> 有空提交一个修复吗？

没问题
