### ISSUE TITLE
[Bug] Win11 不兼容

### ISSUE THREAD

**Issue by shawicx** [RubyMetric/chsrc#82]
### 你操作了什么？

`curl https://gitee.com/RubyMetric/chsrc/releases/download/pre/chsrc-x64-windows.exe -o chsrc.exe`

使用以上命令安装或者直接下载对应安装包，下载完成之后 报错无法使用

![屏幕截图 2024-09-22 100318](https://github.com/user-attachments/assets/a22d4d0a-b7dc-4810-a13c-1e1fdc6f5ae3)

### 发生了什么？

找不到 .dll 文件 无法使用。（兼容问题）

### 本应该怎么样？

chsrc 在 win 11上可以正常使用

### chsrc 版本

0.1.8

### 你使用的是哪个操作系统？

Windows

### OS 版本 / OS 发行版

Windows 11 专业版 23H2 22631.4169

### 防止重复问题

- [X] 我已在项目的 GitHub 和 Gitee 两个仓库分别搜索过类似的 issue

**Comment by ccmywish** [comment]
🤝感谢反馈，已发布 `v0.1.9.beta2`

可重新使用README中的链接下载最新版使用，若无问题，可随时关闭该issue.

**Comment by ccmywish** [comment]
`v0.1.9` 已发布，若仍有问题可开一个新的issue.
