### ISSUE TITLE
[New Target] Bun

### ISSUE THREAD

**Issue by xxnuo** [RubyMetric/chsrc#83]
### 描述新的换源目标

软件

### 请尽可能提供可参考的换源方法

https://bun.sh/guides/install/custom-registry

### 请尽可能提供已有镜像站

同 npm

**Comment by ccmywish** [comment]
@xxnuo

有没有直接的命令可以直接换源？

只能通过编辑 `bunfig.toml` 这个文件实现吗？

**Comment by xxnuo** [comment]
看文档是这样的，我去翻翻源码看看

**Comment by xxnuo** [comment]
目前来看是只有这一个方式

**Comment by ccmywish** [comment]
目前已经实现了最简单的方案——让用户手动写文件。

若日后有更方便的换源方案，可以重新开 issue.

**Comment by ccmywish** [comment]
1. https://bun.sh/docs/runtime/bunfig#global-vs-local
2. #90
