### ISSUE TITLE
[New Source] Nodejs

### ISSUE THREAD

**Issue by xxnuo** [RubyMetric/chsrc#84]
### 描述该源

{
  "yarn": {
    "home": "https://yarnpkg.com",
    "registry": "https://registry.yarnpkg.com/"
  },
  "tencent": {
    "home": "https://mirrors.cloud.tencent.com/npm/",
    "registry": "https://mirrors.cloud.tencent.com/npm/"
  },
  "npmMirror": {
    "home": "https://skimdb.npmjs.com/",
    "registry": "https://skimdb.npmjs.com/registry/"
  }
}

**Comment by ccmywish** [comment]
@xxnuo 你好，感谢对源的提供，有几个问题：

1. `yarn` 的这个 registry 的内容 和 npm 的内容是一样的吗？

    如果是一样的，为什么 `yarn` 自己提供了这么一个镜像？另外，`yarn` 的这个源的速度国内访问情况如何？

2. 我不了解 `skimdb`，简单查了一下，似乎是用来获取registry的元信息的。而具体包的下载位置似乎并不在这里。把skimdb当做源来替换，下载位置是被定向到哪里了？国内访问速度如何？

**Comment by xxnuo** [comment]
我是因为 taobao 源下载 electron 相关的包非常的慢，就翻了 nvm 里有的源，看这里没有所以就补充上来了，你看合适的话就加上呗。我目前是在用 tencent 的源。

> 1. `yarn` 的这个 registry 的内容 和 npm 的内容是一样的吗？
>    如果是一样的，为什么 `yarn` 自己提供了这么一个镜像？另外，`yarn` 的这个源的速度国内访问情况如何？

https://yarnpkg.com/getting-started/qa#why-registryyarnpkgcom-does-facebook-track-us
简而言之就是 npm 的一个只读反向代理。速度的话我不太好测试，因为速度都挺快的。

> 2. 我不了解 `skimdb`，简单查了一下，似乎是用来获取registry的元信息的。而具体包的下载位置似乎并不在这里。把skimdb当做源来替换，下载位置是被定向到哪里了？国内访问速度如何？

skimdb.npmjs.com 是 npm 注册表的一个镜像，它提供了一个与官方注册表相同的数据库副本，但可能位于不同的地理位置或服务器上。

**Comment by ccmywish** [comment]
已添加腾讯的镜像源，另外两个由于国内访问没有什么意义，所以未添加。
