### ISSUE TITLE
[Bug] fedora 38-41上换源失败 

### ISSUE THREAD

**Issue by happy-drink** [RubyMetric/chsrc#93]
### 你操作了什么？

我运行了chsrc set fedora

### 发生了什么？

在fedora38上在下载metadata时失败
![image](https://github.com/user-attachments/assets/2fd2794c-5f5b-49b6-8252-e04d9bb9ecbd)

在fedora39-41上，chsrc对镜像测速并给出了最快的镜像源，但是随后换源的时候失败，因为丢失了两个文件   `/etc/yum.repos.d/fedora-modular.repo `和`/etc/yum.repos.d/fedora-updates-modular.repo`。
![image](https://github.com/user-attachments/assets/a1e901a5-2247-43ff-b958-dfbeb60d3a58)
我查阅过ustc的换源指南发现在fedora39以上移除了这两个文件
![image](https://github.com/user-attachments/assets/17c2e585-ec9f-43bb-b3eb-9b8e35424209)

### 本应该怎么样？

我希望chsrc能够识别fedora版本自动区分版本39以上及以下的情况，或者设置chsrc set fedora的默认版本为39以上的，38及以下的设置为fedora-38之类的做区分。

### chsrc 版本

v0.1.9.Beta4-2024/10/03

### 你使用的是哪个操作系统？

Linux

### OS 版本 / OS 发行版

fedora 40

### Log 输出

```shell
[chsrc 测速] 测速中

  - 阿里巴巴开源镜像站(公网) ... 459.91 KByte/s
  - 北京外国语大学开源软件镜像站 ... 78.57 MByte/s
  - 中国科学技术大学开源镜像站 ... 46.42 MByte/s
  - 清华大学开源软件镜像站 ... 10.89 MByte/s
  - 腾讯软件源(公网) ... 18.75 MByte/s
  - 网易开源镜像站 ... 747.40 KByte/s
  - 搜狐开源镜像站 ... 48.65 KByte/s

最快镜像站: 北京外国语大学开源软件镜像站
选中镜像站: BFSU (bfsu)
--------------------------------
[chsrc 提示] Fedora 29 及以下版本暂不支持
[chsrc 运行] cp /etc/yum.repos.d/fedora.repo /etc/yum.repos.d/fedora.repo.bak --backup='t'
[chsrc 提示] 备份文件名为 /etc/yum.repos.d/fedora.repo.bak
[chsrc 运行] cp /etc/yum.repos.d/fedora-updates.repo /etc/yum.repos.d/fedora-updates.repo.bak --backup='t'
[chsrc 提示] 备份文件名为 /etc/yum.repos.d/fedora-updates.repo.bak
[chsrc 运行] sed -e 's|^metalink=|#metalink=|g' -e 's|^#baseurl=http://download.example/pub/fedora/linux/|baseurl=https://mirrors.bfsu.edu.cn/fedora|g' -i.bak /etc/yum.repos.d/fedora.repo /etc/yum.repos.d/fedora-modular.repo /etc/yum.repos.d/fedora-updates.repo /etc/yum.repos.d/fedora-updates-modular.repo
```

### 防止重复问题

- [X] 我已在项目的 GitHub 和 Gitee 两个仓库分别搜索过类似的 issue

**Comment by happy-drink** [comment]
log输出漏了几行，完整如下:
```
[chsrc 测速] 测速中

  - 阿里巴巴开源镜像站(公网) ... 459.91 KByte/s
  - 北京外国语大学开源软件镜像站 ... 78.57 MByte/s
  - 中国科学技术大学开源镜像站 ... 46.42 MByte/s
  - 清华大学开源软件镜像站 ... 10.89 MByte/s
  - 腾讯软件源(公网) ... 18.75 MByte/s
  - 网易开源镜像站 ... 747.40 KByte/s
  - 搜狐开源镜像站 ... 48.65 KByte/s

最快镜像站: 北京外国语大学开源软件镜像站
选中镜像站: BFSU (bfsu)
--------------------------------
[chsrc 提示] Fedora 29 及以下版本暂不支持
[chsrc 运行] cp /etc/yum.repos.d/fedora.repo /etc/yum.repos.d/fedora.repo.bak --backup='t'
[chsrc 提示] 备份文件名为 /etc/yum.repos.d/fedora.repo.bak
[chsrc 运行] cp /etc/yum.repos.d/fedora-updates.repo /etc/yum.repos.d/fedora-updates.repo.bak --backup='t'
[chsrc 提示] 备份文件名为 /etc/yum.repos.d/fedora-updates.repo.bak
[chsrc 运行] sed -e 's|^metalink=|#metalink=|g' -e 's|^#baseurl=http://download.example/pub/fedora/linux/|baseurl=https://mirrors.bfsu.edu.cn/fedora|g' -i.bak /etc/yum.repos.d/fedora.repo /etc/yum.repos.d/fedora-modular.repo /etc/yum.repos.d/fedora-updates.repo /etc/yum.repos.d/fedora-updates-modular.repo
sed: can't read /etc/yum.repos.d/fedora-modular.repo: No such file or directory
sed: can't read /etc/yum.repos.d/fedora-updates-modular.repo: No such file or directory
[chsrc 运行] x 命令执行失败，退出状态: 512
chsrc: 关键错误，强制结束
```

**Comment by ccmywish** [comment]
感谢提供对fedora换源的反馈，👍

1. `fedora38` 那个404是怎么回事你这边清楚吗？

2. 你觉得是否可以直接用 `fedora*.repo` 来替换？从而不再刻意区分 39以上 或者 38以下

 fedora换源一直没有人测试和使用，有没有兴趣尝试直接修改提交PR？

 https://github.com/RubyMetric/chsrc/blob/main/src/recipe/os/YUM/Fedora-Linux.c

**Comment by happy-drink** [comment]
> 感谢提供对fedora换源的反馈，👍
> 
> 1. `fedora38` 那个404是怎么回事你这边清楚吗？
> 2. 你觉得是否可以直接用 `fedora*.repo` 来替换？从而不再刻意区分 39以上 或者 38以下
> 
> fedora换源一直没有人测试和使用，有没有兴趣尝试直接修改提交PR？
> 
> https://github.com/RubyMetric/chsrc/blob/main/src/recipe/os/YUM/Fedora-Linux.c

1、这是由于在 [https://mirrors.tuna.tsinghua.edu.cn/fedora/releases/38](https://mirrors.tuna.tsinghua.edu.cn/fedora/releases/38)中已经移除了所有内容，只剩下一个REDME，内容如下
![image](https://github.com/user-attachments/assets/e1b9e94e-97b8-4823-9d44-1f4a819c63e0)
在访问里面的网址后它告诉我是因为该版本已经不再维护了(fedora 38官方支持到2023 05/18),所以被移除了。

镜像源的初始文件为
```
[fedora]
name=Fedora $releasever - $basearch
#baseurl=http://download.example/pub/fedora/linux/releases/$releasever/Everything/$basearch/os/
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch
```
而换源脚本会注释掉metalink,使用baseurl，所以会404，可以通过取消注释metalink来解决这个问题，[metalink的作用如下](https://mirrors.ustc.edu.cn/help/fedora.html)
![image](https://github.com/user-attachments/assets/18d7678a-c4b1-48d7-bb2a-7c6c0af99321)

但这样和未换源前没有区别，反而增加了一些额外的改动。

2、我会试着去修复fedora换源的问题，但这可能需要一点时间，感谢你的信任。

**Comment by ccmywish** [comment]
👍👍👍

1. 既然`fedora38`不再维护了，各个镜像站是不是也没有提供对 `archive/fedora` 的镜像了？

    如果是这样，`chsrc` 可以无需再支持 fedora38 及以下

2. metalink这个我也是第一次知道，似乎换源变得不那么需要了

    对此，我觉得可以只换 baseurl，保持 metalink 不动（链接不换，并保持开启），最后仅提示用户如果用户不想使用metalink了，让用户自己手动去注释掉。这样最简单，充分尊重 metalink 的作用。并且也能对暂不知道 metalink 的用户进行一定的概念普及。


## PR

时间上没有问题，不必着急，等你这个PR提交后，我将正式发布 `v0.1.9` 版。

你可以参考这两处地方：

1. https://github.com/RubyMetric/chsrc/blob/main/doc/Write-A-Recipe-Even-If-You-Dont-Know-C.md
2. https://github.com/RubyMetric/chsrc?tab=readme-ov-file#%EF%B8%8F-%E5%BC%80%E5%8F%91

**Comment by happy-drink** [comment]
我在测试的时候出现了一个新的问题，`chsrc_run ("dnf makecache", RunOpt_No_Last_New_Line);`的输出与`hsrc_yield_source_and_confirm (os_fedora);`的输出混在一起了，日志如下:
```
[chsrc 测速] 测速中

  - 阿里巴巴开源镜像站(公网) ... 491.81 KByte/s
  - 北京外国语大学开源软件镜像站 ... 95.45 MByte/s
  - 中国科学技术大学开源镜像站 ... 52.13 MByte/s
  - 清华大学开源软件镜像站 ... 14.45 MByte/s
  - 腾讯软件源(公网) ... 24.89 MByte/s
  - 网易开源镜像站 ... 682.28 KByte/s
  - 搜狐开源镜像站 ... Fedora 40 - x86_64                              8.5 MB/s |  20 MB     00:02    
Fedora 40 openh264 (From Cisco) - x86_64        433  B/s | 1.4 kB     00:03    
Fedora 40 - x86_64 - Updates                    2.1 MB/s |  10 MB     00:04    
Metadata cache created.
39.88 KByte/s

最快镜像站: 北京外国语大学开源软件镜像站
选中镜像站: BFSU (bfsu)
--------------------------------
[chsrc 提示] Fedora 38 及以下版本暂不支持
[chsrc 运行] cp /etc/yum.repos.d/fedora.repo /etc/yum.repos.d/fedora.repo.bak --backup='t'
[chsrc 提示] 备份文件名为 /etc/yum.repos.d/fedora.repo.bak
[chsrc 运行] cp /etc/yum.repos.d/fedora-updates.repo /etc/yum.repos.d/fedora-updates.repo.bak --backup='t'
[chsrc 提示] 备份文件名为 /etc/yum.repos.d/fedora-updates.repo.bak
[chsrc 运行] sed -e 's|^#baseurl=http://download.example/pub/fedora/linux/|baseurl=https://mirrors.bfsu.edu.cn/fedora|g' -i.bak /etc/yum.repos.d/fedora.repo /etc/yum.repos.d/fedora-updates.repo
[chsrc 运行] ✓ 命令执行成功

[chsrc LOG] 已替换文件 /etc/yum.repos.d/fedora.repo
[chsrc LOG] 已替换文件 /etc/yum.repos.d/fedora-updates.repo
[chsrc 提示] chsrc 已为您更换baseurl, 但fedora默认会优先使用metalink来匹配最快的源, 如您在获取metadata时速度较慢可自行将其注释
[chsrc 运行] dnf makecache
[chsrc 运行] ✓ 命令执行成功
--------------------------------
chsrc: 全自动换源完成, 感谢镜像提供方: 北京外国语大学开源软件镜像站
```
当我试着加一行`  chsrc_run ("echo test", RunOpt_Default);`也有这个问题，因此我猜测可能是没有处理好子程序的输出。

**Comment by happy-drink** [comment]
> 👍👍👍
> 
> 1. 既然`fedora38`不再维护了，各个镜像站是不是也没有提供对 `archive/fedora` 的镜像了？
>    如果是这样，`chsrc` 可以无需再支持 fedora38 及以下
> 2. metalink这个我也是第一次知道，似乎换源变得不那么需要了
>    对此，我觉得可以只换 baseurl，保持 metalink 不动（链接不换，并保持开启），最后仅提示用户如果用户不想使用metalink了，让用户自己手动去注释掉。这样最简单，充分尊重 metalink 的作用。并且也能对暂不知道 metalink 的用户进行一定的概念普及。
> 
> ## PR
> 时间上没有问题，不必着急，等你这个PR提交后，我将正式发布 `v0.1.9` 版。
> 
> 你可以参考这两处地方：
> 
> 1. https://github.com/RubyMetric/chsrc/blob/main/doc/Write-A-Recipe-Even-If-You-Dont-Know-C.md
> 2. https://github.com/RubyMetric/chsrc?tab=readme-ov-file#%EF%B8%8F-%E5%BC%80%E5%8F%91

1、镜像站看到 `archive/fedora` 的镜像，因此对于不再支持的fedora版本我认为直接使用Metalink更好。


> 感谢提供对fedora换源的反馈，👍
> 
> 1. `fedora38` 那个404是怎么回事你这边清楚吗？
> 2. 你觉得是否可以直接用 `fedora*.repo` 来替换？从而不再刻意区分 39以上 或者 38以下
> 
> fedora换源一直没有人测试和使用，有没有兴趣尝试直接修改提交PR？
> 
> https://github.com/RubyMetric/chsrc/blob/main/src/recipe/os/YUM/Fedora-Linux.c

2. 我认为不太妥当，因为该文件夹下可能会有一些用户自行添加的仓库，贸然使用 `fedora*.repo` 可能会有不可预测的结果。我觉得还是放弃38以下的支持，对于39以上则使用ustc的换源参考步骤并保留metalink。

**Comment by ccmywish** [comment]
按理说 log混在一起，是不可能出现的事情，因为 `chsrc_yield_source_and_confirm()` 执行的非常简单。

但是结合下面你的 log中 `dnf makecache` 的输出结果：我觉得是 `dnf makecache` 并没有执行完成，而是在后台继续输出？
```
[chsrc 运行] dnf makecache
[chsrc 运行] ✓ 命令执行成功
```

**Comment by ccmywish** [comment]
https://github.com/RubyMetric/chsrc/blob/main/src/chsrc-framework.h#L976

`dnf makecache` 就是直接通过 `system()` 调用的，应该没有什么会导致输出混在一起。

**Comment by happy-drink** [comment]
> https://github.com/RubyMetric/chsrc/blob/main/src/chsrc-framework.h#L976
> 
> `dnf makecache` 就是直接通过 `system()` 调用的，应该没有什么会导致输出混在一起。

这个问题出现在我运行'docker run -v $PWD:/app -w /app fedora:40 ./chsrc set fedora '，在正常启动docker并手动运行是没问题的，也许问题出在docker那里
