### ISSUE TITLE
[Bug] winget source remove winget错误地显示"成功",需增加判断以预防

### ISSUE THREAD

**Issue by saltglow** [RubyMetric/chsrc#94]
### 你操作了什么？

chsrc set winget

### 发生了什么？

换源没有成功

但是第二次执行相同命令却成功了

值得一提的是,我曾经手动更改过winget源,或许这次错误和我不规范的换源有关系.但那次的操作记录,我实在找不到了,抱歉.

### 本应该怎么样？

或许应当再检测一次winget当前源,仍然存在就重复执行删除命令/sleep等待改变/重启pwsh

### chsrc 版本

Change Source (GPLv3+) [35mv0.1.8-2024/08/23[0m by RubyMetric

### 你使用的是哪个操作系统？

Windows

### OS 版本 / OS 发行版

10.0.19045 暂缺 Build 19045

### Log 输出

```shell
[chsrc 检查] ✓ 命令 curl 存在
测速 https://mirrors.ustc.edu.cn/ ... 23.69 MByte/s
chsrc: 中国科学技术大学开源镜像站 是 winget 目前唯一可用镜像站，感谢他们的慷慨支持
选中镜像站: USTC (ustc)
--------------------------------
[chsrc 运行] winget source remove winget
正在删除源: winget...
  ██████████████████████████████  100%
完成
[chsrc 运行] ✓ 命令执行成功

[chsrc 运行] winget source add winget https://mirrors.ustc.edu.cn/winget-source
具有给定名称的源已存在，并且引用了其他位置:
  winget -> https://cdn.winget.microsoft.com/cache
[chsrc 运行] x 命令执行失败，返回码 -1978335220
chsrc: 关键错误，强制结束
```

### 防止重复问题

- [X] 我已在项目的 GitHub 和 Gitee 两个仓库分别搜索过类似的 issue

**Comment by saltglow** [comment]
问题其实不大,甚至再次运行就解决了,但其中的缘由我实在不能理解.
请问 我应当现在关闭这个议题吗?

**Comment by saltglow** [comment]
哦,糟糕,我搞错了两次return,第一次的return实际上如下:
[chsrc 检查] ✓ 命令 curl 存在
测速 https://mirrors.ustc.edu.cn/ ... 23.69 MByte/s
chsrc: 中国科学技术大学开源镜像站 是 winget 目前唯一可用镜像站，感谢他们的慷慨支持
选中镜像站: USTC (ustc)
--------------------------------
[chsrc 运行] winget source remove winget
正在删除源: winget...
  ██████████████████████████████  100%
完成
[chsrc 运行] ✓ 命令执行成功

[chsrc 运行] winget source add winget https://mirrors.ustc.edu.cn/winget-source
具有给定名称的源已存在，并且引用了其他位置:
  winget -> https://cdn.winget.microsoft.com/cache
[chsrc 运行] x 命令执行失败，返回码 -1978335220
chsrc: 关键错误，强制结束

**Comment by ccmywish** [comment]
🤝 @saltglow 感谢反馈，问题已确认

**Comment by saltglow** [comment]
感谢解惑！
