### ISSUE TITLE
考虑提供短链接安装

### ISSUE THREAD

**Issue by Jerry-Terrasse** [RubyMetric/chsrc#97]
目前的安装命令（`curl -L https://gitee.com/RubyMetric/chsrc/releases/download/pre/chsrc-x64-linux -o chsrc; chmod +x ./chsrc`）较长，不便于在刚装好的没有图形界面或没有浏览器的系统上快速获取并换源。因此建议提供方便的短链接安装方式 :)

一个可能比较好的实现方案是：提供一个短链接下载统一的安装脚本，脚本自动获取系统和架构等信息，随后直接下载对应的二进制，无需用户手动选择和复制长链接。

例如`pyenv`的自动安装：
```
curl https://pyenv.run | bash
```

**Comment by ccmywish** [comment]
短链，弄了个 `chsrc.run` 的域名，打算转到 `rubymetric.github.io` 来处理。

**Comment by ccmywish** [comment]
我发布了一个新的 issue，邀请看到的人参与贡献。若没时间，可以让有意愿的人来帮忙完成 🤝

#98

**Comment by ccmywish** [comment]
已启用 https://chsrc.run/

原理是部署到 `gh-site` 分支：https://github.com/RubyMetric/chsrc/tree/gh-site/docs

可以这么使用：

```bash
# Linux 和 macOS
$ curl https:/chsrc.run/posix | bash

# Windows
$ iwr -useb "https://chsrc.run/windows" | iex
```

**Comment by ccmywish** [comment]
现在有一个问题，这个 
1. `gh-site` 分支的 `docs/posix` 文件就是 `main` 分支的 `tool/install.sh` 
2. `gh-site` 分支的 `docs/windows` 文件就是 `main` 分支的 `tool/install.ps1`

`gh-site` 分支**不**和 `main` 分支保持同步，**仅仅同步上述两个文件**。

每次修改 `tool/install.sh` 和 `tool/install.ps1` 的时候，我都需要手动切换分支并复制粘贴到那里，很可能容易忘记。能否帮忙写一个小的 action 来完成这件事？其实不写也行，主要是怕忘记。你有时间的时候，可以帮忙做一下这个。不急，时间完全随意。🤝

**Comment by Jerry-Terrasse** [comment]
可以的 :handshake:

**Comment by ccmywish** [comment]
我觉得这个可以不用再花时间做了，因为改动不会很频繁 ❤️

**Comment by ccmywish** [comment]
才发现，待会儿改一下。不过似乎这样也是可以直接运行的。。

![image](https://github.com/user-attachments/assets/92b914f6-ed9c-406f-96b5-b442cedc21d9)

**Comment by Jerry-Terrasse** [comment]
看来curl是支持自动纠错的 :+1:
